apiVersion: v1
kind: Service
metadata:
  name: dycel-service
  labels:
    app: dycel
spec:
  type: NodePort
  selector:
    app: dycel
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007 
